version: '3'

# Отключает вывод команд в консоль для всего файла
silent: true

tasks:
  default:
    desc: Показать список всех доступных команд
    cmds:
      - task --list

  todo-to-issue:
    # Автоматическое (при помощи LLM) создание issues в проекте из контекста метки TODO
    desc: Создать issues на основе меток TODO